theme = "native"
[icons]
name = "awesome"


[[block]]
block = "focused_window"
max_width = 80
show_marks = "visible"

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mug}GB/{MTg}GB"
format_swap = "{SUg}GB/{STg}GB"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "networkmanager"
interface_name_exclude = ["br\\-[0-9a-f]{12}", "docker\\d+"]
interface_name_include = []

[[block]]
block = "backlight"

[[block]]
block = "sound"

[[block]]
block = "battery"
interval = 10
format = "{percentage}% {time}"

[[block]]
block = "time"
interval = 60
format = "%a %d/%m %R"
